server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://bungae.cpvuqfsqbscz.ap-northeast-2.rds.amazonaws.com/bungae?autoReconnect=true # 변경해주세요
    username: testUser
    password: pass7987
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전